# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignacion', '0004_detailasignation_culmined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count_payment', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_payment', models.DateTimeField(blank=True, null=True)),
                ('anulate', models.BooleanField(default=False)),
                ('detail_asignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.DetailAsignation')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_created', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
